### ISSUE TITLE
allow to assigne a class

### ISSUE THREAD

**Issue by gb5256** [pavlinter/yii2-display-image#2]
Hi,
It would be cool to be able to add a class to the returned image tag, like this:

    echo DisplayImage::widget([
                'class'=>'customer_img_class',
                'width' => 270,
                'height' => 200,
                'class'=>'asdf',
                'image' => $model->image,
                'category' => 'article',
                'cacheSeconds' => 'auto', //auto is default value. Rewrite image if modified file date is different
            ]);

**Comment by pavlinter** [comment]
```php
echo DisplayImage::widget([
            'options'=>[
                'class'=>'customer_img_class',
            ],
            'width' => 270,
            'height' => 200,
            'image' => $model->image,
            'category' => 'article',
            'cacheSeconds' => 'auto', //auto is default value. Rewrite image if modified file date is different
        ]);
```
It is deprecated widget, New version [pavlinter/yii2-display-image2](https://github.com/pavlinter/yii2-display-image2)
